### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by thegamingstig** [sergioalmela/TwitchDownloader#4]
1. The download appears to be stuck at 7% whether if it is VOD or live. The program terminates itself when downloading a live stream
2. the video file cannot be found when my download path is relative.

**Comment by sergioalmela** [comment]
Hi! Can you please share:

- URL of the content to download
- The local path to save the file
- The resolution

Thank you.

**Comment by thegamingstig** [comment]
VOD: https://www.twitch.tv/videos/1656411723 (stuck at 7% using relative path "/video/kichike.mp4" at source resolution. **File not located**)

Live stream download crashes:
https://www.twitch.tv/kichike (download path at "c:/downloads/kichike2.mp4". File download stopped at 1.49GB at source resolution)
https://www.twitch.tv/rayina (download path at "c/downloads/rayina.mp4". File download stopped at 1.37GB at source resolution)

**Comment by sergioalmela** [comment]
Hi, I just released a new version of the program, make sure you git pull the changes.
The issue was located. It seems that the videos that contain muted parts (protected with copyright) cannot be downloaded, so I have changed the logic to download said parts even if it is without audio, so the video you mention should not give you problems.
About saving files, if you use Windows, note that paths like '/videos/' are saved to C:\ or C:\users. By default, the program tries to create directories that do not exist. If you don't get an error message, the file must be in a directory. I recommend you to use absolute paths like C:/Users/yourUser/Downloads/video.mp4 or similar.

Confirm if the bug still appears.

**Comment by thegamingstig** [comment]
bug still exist

**Comment by sergioalmela** [comment]
Can you confirm it still happens to this video: https://www.twitch.tv/videos/1656411723
Even pulling the latest changes from master?

**Comment by thegamingstig** [comment]
![image](https://user-images.githubusercontent.com/97251471/204076610-f2225821-532a-45f8-bc0f-6d7afdc9cbe1.png)
Still stuck

**Comment by thegamingstig** [comment]
Sorry, it appears my reinstallation was not done properly. It works now. Thank you!
